### ISSUE TITLE
craft

### ISSUE THREAD

**Issue by q7c** [DenisMasterHerobrine/ASoD-ExpertMode#1]
Check craft Energy Collerctor MK1 in ProjectE
![xXvphk8 1](https://user-images.githubusercontent.com/5392773/63452871-09104600-c450-11e9-84c2-fc703b983caf.png)

**Comment by DenisMasterHerobrine** [comment]
Thanks for the report, fixed in Expert Mode 1.2.4 for Awakening - Sky Of Diamonds 1.4.1.
