### ISSUE TITLE
Energy Condenser ProjectE

### ISSUE THREAD

**Issue by mo3ayka** [DenisMasterHerobrine/ASoD-ExpertMode#2]
![2019-08-25_15 25 09](https://user-images.githubusercontent.com/54501272/63649986-a10e7800-c74d-11e9-8dce-e35fd528d595.png)
![2019-08-25_15 25 11](https://user-images.githubusercontent.com/54501272/63649987-a10e7800-c74d-11e9-85ee-59abac902f2d.png)
![2019-08-25_15 31 32](https://user-images.githubusercontent.com/54501272/63649988-a1a70e80-c74d-11e9-91ce-d80e2743a1aa.png)
![2019-08-25_15 31 43](https://user-images.githubusercontent.com/54501272/63649989-a1a70e80-c74d-11e9-9de0-199daf4b3522.png)

**Comment by DenisMasterHerobrine** [comment]
It's just a visual bug of JEI, will be fixed soon.

**Comment by DenisMasterHerobrine** [comment]
Fixed in v1.2.6 for 1.4.2
